/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useContext, useState, useEffect } from "react";

const translations = {
  uz: {
    // Navigation / Sidebar
    "nav.dashboard": "Asosiy",
    "nav.teachers": "O'qituvchilar",
    "nav.groups": "Guruhlar",
    "nav.students": "Talabalar",
    "nav.gifts": "Sovg'alar",
    "nav.management": "Boshqarish",
    "nav.courses": "Kurslar",
    "nav.rooms": "Xonalar",
    "nav.staff": "Hodimlar",
    "nav.archive": "Arxiv",
    "nav.coin": "Coin",
    "nav.sendMessage": "Xabar Yuborish",

    // Header & Layout
    "header.add": "Qo'shish",
    "header.search": "Qidirish...",
    "header.logout": "Tizimdan chiqish",
    "header.darkMode": "Tungi rejim",
    "header.lightMode": "Kunduzgi rejim",

    // Pages titles & subtitles
    "title.teachers": "O'qituvchilar",
    "subtitle.teachers": "Ushbu sahifada siz o'qituvchilar ro'yxatini va ularning ma'lumotlarini topasiz.",
    "title.students": "Talabalar",
    "subtitle.students": "Ushbu sahifada siz Talabalar ro'yxatini va ularning ma'lumotlarini topasiz.",
    "title.groups": "Guruhlar",
    "subtitle.groups": "Ushbu sahifada siz o'quv markazidagi barcha guruhlar va ularning dars jadvalini ko'rishingiz mumkin.",
    "title.welcome": "Salom",
    "subtitle.welcome": "EduCoin platformasiga xush kelibsiz",
    "title.createHomework": "Yangi uyga vazifa yaratish",
    "title.dashboard": "Boshqaruv paneli",

    // Button actions
    "btn.addTeacher": "O'qituvchi qo'shish",
    "btn.addGroup": "Guruh qo'shish",
    "btn.addStudent": "Talaba qo'shish",
    "btn.export": "Eksport",
    "btn.refresh": "Yangilash",
    "btn.archive": "Arxiv",
    "btn.active": "Faollar",
    "btn.save": "Saqlash",
    "btn.cancel": "Bekor qilish",
    "btn.yes": "Ha",
    "btn.delete": "O'chirish",
    "btn.edit": "Tahrirlash",
    "btn.view": "Ko'rish",
    "btn.deleting": "O'chirilmoqda...",
    "btn.previous": "Oldingi",
    "btn.next": "Keyingi",
    "btn.add": "Qo'shish",

    // Common
    "common.loading": "Yuklanmoqda...",
    "common.noData": "Ma'lumotlar mavjud emas",
    "common.save": "Saqlash",
    "common.cancel": "Bekor qilish",
    "common.delete": "O'chirish",
    "common.edit": "Tahrirlash",
    "common.confirm": "Tasdiqlash",
    "common.search": "Qidirish...",
    "common.page": "Sahifa",
    "common.actions": "Amallar",
    "common.name": "Nomi",
    "common.phone": "Telefon raqamlari",
    "common.email": "Email",
    "common.address": "Manzil",
    "common.createdAt": "Yaratilgan sana",
    "common.group": "Guruh",
    "common.birthDate": "Tug'ilgan sanasi",
    "common.notFound": "Topilmadi",
    "common.status": "Status",

    // Teacher page
    "teacher.notFound": "O'qituvchilar topilmadi.",
    "teacher.deleteTitle": "O'qituvchini o'chirish",
    "teacher.deleteConfirm": "Rostdan ham o'chirishni hohlaysizmi?",
    "teacher.searchPlaceholder": "Qidirish...",

    // Student page
    "student.notFound": "Talabalar topilmadi.",
    "student.searchPlaceholder": "Talaba qidirish...",
    "student.deleteTitle": "Talabani o'chirish",
    "student.deleteConfirm": "Rostdan ham o'chirishni hohlaysizmi?",

    // Groups page
    "group.notFound": "Guruhlar topilmadi.",
    "group.searchPlaceholder": "Guruh qidirish...",
    "group.deleteTitle": "Guruhni o'chirish",
    "group.deleteConfirm": "Rostdan ham o'chirishni hohlaysizmi?",
    "group.course": "Kurs",
    "group.teacher": "O'qituvchi",
    "group.studentsCount": "Talabalar soni",
    "group.startDate": "Boshlanish sanasi",
    "group.endDate": "Tugash sanasi",
    "group.days": "Kunlar",
    "group.time": "Vaqt",
    "group.room": "Xona",

    // GroupDetails page
    "groupDetail.info": "Ma'lumotlar",
    "groupDetail.syllabus": "Guruh darsliklari",
    "groupDetail.attendance": "Akademik davomati",
    "groupDetail.mentors": "Guruh mentorlari",
    "groupDetail.params": "Parametrlar",
    "groupDetail.schedule": "Dars jadvali",
    "groupDetail.statistics": "Statistika",
    "groupDetail.active": "Aktiv",
    "groupDetail.inactive": "Faol emas",
    "groupDetail.currentMonth": "Joriy oy",
    "groupDetail.showAll": "Barchasini ko'rish",
    "groupDetail.showLess": "Kamroq ko'rsatish",
    "groupDetail.noLessons": "Ushbu oyda darslar rejalashtirilmagan.",
    "groupDetail.homework": "Uyga vazifa",
    "groupDetail.videos": "Videolar",
    "groupDetail.exams": "Imtihonlar",
    "groupDetail.journal": "Jurnal",
    "groupDetail.newExam": "Yangi imtihon",
    "groupDetail.addVideo": "Qo'shish",
    "groupDetail.noHomework": "Ushbu guruhda hali uyga vazifalar mavjud emas.",
    "groupDetail.noVideos": "Ushbu guruhda hali videolar yuklanmagan.",
    "groupDetail.journalEmpty": "Jurnal bo'limi hozircha mavjud emas",
    "groupDetail.topic": "Mavzu",
    "groupDetail.givenTime": "Berilgan vaqt",
    "groupDetail.endTime": "Tugash vaqti",
    "groupDetail.lessonDate": "Dars sanasi",
    "groupDetail.videoName": "Video nomi",
    "groupDetail.lessonName": "Dars nomi",
    "groupDetail.size": "Hajmi",
    "groupDetail.addedTime": "Qo'shilgan vaqti",
    "groupDetail.studentName": "Talaba nomi",
    "groupDetail.total": "Jami",
    "groupDetail.noStudents": "Talabalar mavjud emas.",
    "groupDetail.loading": "Yuklanmoqda...",
    "groupDetail.attendanceLoading": "Davomati yuklanmoqda...",
    "groupDetail.uploadVideoTitle": "Videofaylni yuklash uchun ushbu hudud ustiga bosing yoki faylni shu yerga olib keling",
    "groupDetail.uploadVideoFormat": "Videofayl: .mp4, .webm, .mpeg, .avi, .mkv, .m4v, .ogm, .mov formatlaridan birida bo'lishi kerak",
    "groupDetail.selectLesson": "Darsni tanlang",
    "groupDetail.uploadFiles": "Fayllarni yuklash",
    "groupDetail.videoLoading": "Video yuklanmoqda...",
    "groupDetail.examName": "Imtihon nomi",
    "groupDetail.examStartTime": "Boshlanish vaqti",
    "groupDetail.examDuration": "Davomiyligi (daqiqa)",
    "groupDetail.courseLabel": "Kurs:",
    "groupDetail.avgAge": "O'rta yosh:",
    "groupDetail.capacity": "O'quvchilar sig'imi:",
    "groupDetail.currentStudents": "Mavjud o'quvchilar:",
    "groupDetail.monthlyLessons": "O'quv oyidagi darslar soni:",
    "groupDetail.courseDuration": "Kurs davomiyligi (oy):",
    "groupDetail.totalLessons": "Jami darslar soni:",
    "homeworkDetail.waiting": "Kutayotganlar",
    "homeworkDetail.returned": "Qaytarilganlar",
    "homeworkDetail.accepted": "Qabul qilinganlar",
    "homeworkDetail.unsubmitted": "Bajarilmagan",
    "homeworkDetail.gradeHomework": "Uyga vazifani baholash",
    "homeworkDetail.submittedTime": "Topshirilgan vaqt:",
    "homeworkDetail.notSubmitted": "Topshirilmagan",
    "homeworkDetail.filesCount": "Fayllar / Linklar soni:",
    "homeworkDetail.status": "Hozirgi status:",
    "homeworkDetail.studentComment": "O'quvchi izohi va havolalar:",
    "homeworkDetail.gradingBanner": "60-100 oralig'ida ball qo'yilgan vazifa 'Qabul qilingan', 0-59 oralig'ida ball qo'yilgan vazifa 'Qaytarilgan' hisoblanadi.",
    "homeworkDetail.score": "Ball",
    "homeworkDetail.passingScore": "O'tish bali: 60",
    "homeworkDetail.teacherCommentPlaceholder": "Izohingiz",
    "homeworkDetail.voiceInput": "Ovozli kiritish (Voice input)",
    "homeworkDetail.studentName": "O'quvchi ismi",
    "homeworkDetail.submittedAt": "Uyga vazifa jo'natilgan vaqt",
    "homeworkDetail.sectionEmpty": "Bu bo'limda o'quvchilar mavjud emas",
    "homeworkDetail.successGraded": "Ball va izoh muvaffaqiyatli yuborildi!",
    "examDetail.examTask": "Imtihon vazifasi",
    "examDetail.examComment": "Imtihon izohi:",
    "examDetail.studentList": "Talabalar ro'yxati",
    "examDetail.noStudentsSubmitted": "Hech qaysi talaba topshirmagan",
    "examDetail.successScore": "Ball muvaffaqiyatli yuborildi!",
    "lessonAttendance.backToGroup": "Guruhga qaytish",
    "lessonAttendance.lessonAttendance": "Dars yo'qlamasi",
    "lessonAttendance.info": "Ma'lumot",
    "lessonAttendance.lessonDate": "Dars kuni",
    "lessonAttendance.status": "Holat",
    "lessonAttendance.lessonCompleted": "Dars o'tilgan",
    "lessonAttendance.lessonNotCompleted": "Dars o'tilmagan",
    "lessonAttendance.attendanceAndTopic": "Yo'qlama va mavzu kiritish",
    "lessonAttendance.bySyllabus": "O'quv reja bo'yicha",
    "lessonAttendance.other": "Boshqa",
    "lessonAttendance.topic": "Mavzu",
    "lessonAttendance.descriptionOptional": "Tavsif (ixtiyoriy)",
    "lessonAttendance.descriptionPlaceholder": "Dars haqida qo'shimcha ma'lumot...",
    "lessonAttendance.attended": "Keldi",
    "lessonAttendance.lessonAlreadySaved": "Dars allaqachon saqlangan",
    "createHomework.createHomework": "Yangi uyga vazifa yaratish",
    "createHomework.createExam": "Imtihon yaratish",
    "createHomework.selectTopic": "Mavzulardan birini tanlang",
    "createHomework.loadingTopics": "Mavzular yuklanmoqda...",
    "createHomework.description": "Izoh",
    "createHomework.descriptionPlaceholderHW": "Vazifa haqida batafsil ma'lumot kiriting...",
    "createHomework.descriptionPlaceholderExam": "Imtihon haqida batafsil ma'lumot kiriting...",
    "createHomework.selectFileOrDrag": "Faylni tanlash yoki shu yerga tashlang",
    "createHomework.allowedFormats": "PDF, Word, ZIP va boshqa formatlar",
    "createHomework.publish": "E'lon qilish",
    "createHomework.selectTopicError": "Iltimos, mavzuni tanlang!",
    "createHomework.enterCommentError": "Iltimos, izoh kiriting!",
    "createHomework.successPublish": "Uyga vazifa muvaffaqiyatli e'lon qilindi!",
    "createHomework.successPublishExam": "Imtihon muvaffaqiyatli yaratildi!",
    "createHomework.examWarningBanner": "Oxirgi 7 kundagi uyga vazifa berilmagan mavzularni tanlay olasiz!",
    "createHomework.enterEndDateError": "Iltimos, tugash sanasini kiriting!",
    "createHomework.enterEndTimeError": "Iltimos, tugash vaqtini kiriting!",
    "createHomework.endDate": "Tugash sanasi",
    "createHomework.endTime": "Tugash vaqti",
    "createHomework.enterDatePlaceholder": "Sanani kiriting",
    "createHomework.enterTimePlaceholder": "Vaqtni kiriting",
    "createHomework.upload": "Yuklash",
  },
  ru: {
    // Navigation / Sidebar
    "nav.dashboard": "Главная",
    "nav.teachers": "Учителя",
    "nav.groups": "Группы",
    "nav.students": "Студенты",
    "nav.gifts": "Подарки",
    "nav.management": "Управление",
    "nav.courses": "Курсы",
    "nav.rooms": "Комнаты",
    "nav.staff": "Сотрудники",
    "nav.archive": "Архив",
    "nav.coin": "Коин",
    "nav.sendMessage": "Отправить сообщение",

    // Header & Layout
    "header.add": "Добавить",
    "header.search": "Поиск...",
    "header.logout": "Выйти",
    "header.darkMode": "Темная тема",
    "header.lightMode": "Светлая тема",

    // Pages titles & subtitles
    "title.teachers": "Учителя",
    "subtitle.teachers": "На этой странице вы найдете список учителей и информацию о них.",
    "title.students": "Студенты",
    "subtitle.students": "На этой странице вы найдете список студентов и информацию о них.",
    "title.groups": "Группы",
    "subtitle.groups": "На этой странице вы можете просмотреть все группы учебного центра и их расписание уроков.",
    "title.welcome": "Привет",
    "subtitle.welcome": "Добро пожаловать на платформу EduCoin",
    "title.createHomework": "Создать новое домашнее задание",
    "title.dashboard": "Панель управления",

    // Button actions
    "btn.addTeacher": "Добавить учителя",
    "btn.addGroup": "Добавить группу",
    "btn.addStudent": "Добавить студента",
    "btn.export": "Экспорт",
    "btn.refresh": "Обновить",
    "btn.archive": "Архив",
    "btn.active": "Активные",
    "btn.save": "Сохранить",
    "btn.cancel": "Отмена",
    "btn.yes": "Да",
    "btn.delete": "Удалить",
    "btn.edit": "Редактировать",
    "btn.view": "Просмотр",
    "btn.deleting": "Удаление...",
    "btn.previous": "Назад",
    "btn.next": "Вперёд",
    "btn.add": "Добавить",

    // Common
    "common.loading": "Загрузка...",
    "common.noData": "Нет данных",
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.delete": "Удалить",
    "common.edit": "Редактировать",
    "common.confirm": "Подтвердить",
    "common.search": "Поиск...",
    "common.page": "Страница",
    "common.actions": "Действия",
    "common.name": "Имя",
    "common.phone": "Телефон",
    "common.email": "Email",
    "common.address": "Адрес",
    "common.createdAt": "Дата создания",
    "common.group": "Группа",
    "common.birthDate": "Дата рождения",
    "common.notFound": "Не найдено",
    "common.status": "Статус",

    // Teacher page
    "teacher.notFound": "Учителя не найдены.",
    "teacher.deleteTitle": "Удалить учителя",
    "teacher.deleteConfirm": "Вы действительно хотите удалить?",
    "teacher.searchPlaceholder": "Поиск...",

    // Student page
    "student.notFound": "Студенты не найдены.",
    "student.searchPlaceholder": "Поиск студента...",
    "student.deleteTitle": "Удалить студента",
    "student.deleteConfirm": "Вы действительно хотите удалить?",

    // Groups page
    "group.notFound": "Группы не найдены.",
    "group.searchPlaceholder": "Поиск группы...",
    "group.deleteTitle": "Удалить группу",
    "group.deleteConfirm": "Вы действительно хотите удалить?",
    "group.course": "Курс",
    "group.teacher": "Учитель",
    "group.studentsCount": "Кол-во студентов",
    "group.startDate": "Дата начала",
    "group.endDate": "Дата окончания",
    "group.days": "Дни",
    "group.time": "Время",
    "group.room": "Комната",

    // GroupDetails page
    "groupDetail.info": "Информация",
    "groupDetail.syllabus": "Учебники группы",
    "groupDetail.attendance": "Академическая посещаемость",
    "groupDetail.mentors": "Менторы группы",
    "groupDetail.params": "Параметры",
    "groupDetail.schedule": "Расписание занятий",
    "groupDetail.statistics": "Статистика",
    "groupDetail.active": "Активный",
    "groupDetail.inactive": "Не активный",
    "groupDetail.currentMonth": "Текущий месяц",
    "groupDetail.showAll": "Показать все",
    "groupDetail.showLess": "Скрыть",
    "groupDetail.noLessons": "В этом месяце занятия не запланированы.",
    "groupDetail.homework": "Домашнее задание",
    "groupDetail.videos": "Видео",
    "groupDetail.exams": "Экзамены",
    "groupDetail.journal": "Журнал",
    "groupDetail.newExam": "Новый экзамен",
    "groupDetail.addVideo": "Добавить",
    "groupDetail.noHomework": "В этой группе ещё нет домашних заданий.",
    "groupDetail.noVideos": "В этой группе ещё нет загруженных видео.",
    "groupDetail.journalEmpty": "Раздел журнала пока недоступен",
    "groupDetail.topic": "Тема",
    "groupDetail.givenTime": "Время выдачи",
    "groupDetail.endTime": "Срок сдачи",
    "groupDetail.lessonDate": "Дата урока",
    "groupDetail.videoName": "Название видео",
    "groupDetail.lessonName": "Название урока",
    "groupDetail.size": "Размер",
    "groupDetail.addedTime": "Время добавления",
    "groupDetail.studentName": "Имя студента",
    "groupDetail.total": "Итого",
    "groupDetail.noStudents": "Студенты отсутствуют.",
    "groupDetail.loading": "Загрузка...",
    "groupDetail.attendanceLoading": "Загрузка посещаемости...",
    "groupDetail.uploadVideoTitle": "Нажмите на эту область или перетащите файл сюда для загрузки видео",
    "groupDetail.uploadVideoFormat": "Видеофайл должен быть в одном из форматов: .mp4, .webm, .mpeg, .avi, .mkv, .m4v, .ogm, .mov",
    "groupDetail.selectLesson": "Выберите урок",
    "groupDetail.uploadFiles": "Загрузить файлы",
    "groupDetail.videoLoading": "Видео загружается...",
    "groupDetail.examName": "Название экзамена",
    "groupDetail.examStartTime": "Время начала",
    "groupDetail.examDuration": "Продолжительность (мин)",
    "groupDetail.courseLabel": "Курс:",
    "groupDetail.avgAge": "Средний возраст:",
    "groupDetail.capacity": "Вместимость:",
    "groupDetail.currentStudents": "Текущих студентов:",
    "groupDetail.monthlyLessons": "Уроков в учебном месяце:",
    "groupDetail.courseDuration": "Продолжительность курса (мес):",
    "groupDetail.totalLessons": "Всего уроков:",
    "homeworkDetail.waiting": "Ожидающие",
    "homeworkDetail.returned": "Возвращенные",
    "homeworkDetail.accepted": "Принятые",
    "homeworkDetail.unsubmitted": "Не выполненные",
    "homeworkDetail.gradeHomework": "Оценка домашнего задания",
    "homeworkDetail.submittedTime": "Время сдачи:",
    "homeworkDetail.notSubmitted": "Не сдано",
    "homeworkDetail.filesCount": "Кол-во файлов / ссылок:",
    "homeworkDetail.status": "Текущий статус:",
    "homeworkDetail.studentComment": "Комментарий студента и ссылки:",
    "homeworkDetail.gradingBanner": "Задание с оценкой 60-100 считается 'Принятым', 0-59 - 'Возвращенным'.",
    "homeworkDetail.score": "Балл",
    "homeworkDetail.passingScore": "Проходной балл: 60",
    "homeworkDetail.teacherCommentPlaceholder": "Ваш комментарий",
    "homeworkDetail.voiceInput": "Голосовой ввод",
    "homeworkDetail.studentName": "Имя ученика",
    "homeworkDetail.submittedAt": "Время отправки домашнего задания",
    "homeworkDetail.sectionEmpty": "В этом разделе нет студентов",
    "homeworkDetail.successGraded": "Балл и комментарий успешно отправлены!",
    "examDetail.examTask": "Экзаменационное задание",
    "examDetail.examComment": "Комментарий к экзамену:",
    "examDetail.studentList": "Список студентов",
    "examDetail.noStudentsSubmitted": "Ни один студент не сдал",
    "examDetail.successScore": "Балл успешно отправлен!",
    "lessonAttendance.backToGroup": "Вернуться в группу",
    "lessonAttendance.lessonAttendance": "Посещаемость урока",
    "lessonAttendance.info": "Информация",
    "lessonAttendance.lessonDate": "День урока",
    "lessonAttendance.status": "Статус",
    "lessonAttendance.lessonCompleted": "Урок проведен",
    "lessonAttendance.lessonNotCompleted": "Урок не проведен",
    "lessonAttendance.attendanceAndTopic": "Ввод посещаемости и темы",
    "lessonAttendance.bySyllabus": "По учебному плану",
    "lessonAttendance.other": "Другое",
    "lessonAttendance.topic": "Тема",
    "lessonAttendance.descriptionOptional": "Описание (необязательно)",
    "lessonAttendance.descriptionPlaceholder": "Дополнительная информация об уроке...",
    "lessonAttendance.attended": "Пришел",
    "lessonAttendance.lessonAlreadySaved": "Урок уже сохранен",
    "createHomework.createHomework": "Создать новое домашнее задание",
    "createHomework.createExam": "Создать экзамен",
    "createHomework.selectTopic": "Выберите тему",
    "createHomework.loadingTopics": "Загрузка тем...",
    "createHomework.description": "Описание",
    "createHomework.descriptionPlaceholderHW": "Введите подробную информацию о задании...",
    "createHomework.descriptionPlaceholderExam": "Введите подробную информацию об экзамене...",
    "createHomework.selectFileOrDrag": "Выберите файл или перетащите сюда",
    "createHomework.allowedFormats": "Форматы PDF, Word, ZIP и др.",
    "createHomework.publish": "Опубликовать",
    "createHomework.selectTopicError": "Пожалуйста, выберите тему!",
    "createHomework.enterCommentError": "Пожалуйста, введите комментарий!",
    "createHomework.successPublish": "Домашнее задание успешно опубликовано!",
    "createHomework.successPublishExam": "Экзамен успешно создан!",
    "createHomework.examWarningBanner": "Вы можете выбирать только темы без домашнего задания за последние 7 дней!",
    "createHomework.enterEndDateError": "Пожалуйста, введите дату окончания!",
    "createHomework.enterEndTimeError": "Пожалуйста, введите время окончания!",
    "createHomework.endDate": "Дата окончания",
    "createHomework.endTime": "Время окончания",
    "createHomework.enterDatePlaceholder": "Введите дату",
    "createHomework.enterTimePlaceholder": "Введите время",
    "createHomework.upload": "Загрузить",
  },
  en: {
    // Navigation / Sidebar
    "nav.dashboard": "Dashboard",
    "nav.teachers": "Teachers",
    "nav.groups": "Groups",
    "nav.students": "Students",
    "nav.gifts": "Gifts",
    "nav.management": "Management",
    "nav.courses": "Courses",
    "nav.rooms": "Rooms",
    "nav.staff": "Staff",
    "nav.archive": "Archive",
    "nav.coin": "Coin",
    "nav.sendMessage": "Send Message",

    // Header & Layout
    "header.add": "Add",
    "header.search": "Search...",
    "header.logout": "Log out",
    "header.darkMode": "Dark mode",
    "header.lightMode": "Light mode",

    // Pages titles & subtitles
    "title.teachers": "Teachers",
    "subtitle.teachers": "On this page, you will find the list of teachers and their information.",
    "title.students": "Students",
    "subtitle.students": "On this page, you will find the list of students and their details.",
    "title.groups": "Groups",
    "subtitle.groups": "On this page, you can view all learning center groups and their class schedules.",
    "title.welcome": "Hello",
    "subtitle.welcome": "Welcome to the EduCoin platform",
    "title.createHomework": "Create New Homework",
    "title.dashboard": "Dashboard",

    // Button actions
    "btn.addTeacher": "Add Teacher",
    "btn.addGroup": "Add Group",
    "btn.addStudent": "Add Student",
    "btn.export": "Export",
    "btn.refresh": "Refresh",
    "btn.archive": "Archive",
    "btn.active": "Active",
    "btn.save": "Save",
    "btn.cancel": "Cancel",
    "btn.yes": "Yes",
    "btn.delete": "Delete",
    "btn.edit": "Edit",
    "btn.view": "View",
    "btn.deleting": "Deleting...",
    "btn.previous": "Previous",
    "btn.next": "Next",
    "btn.add": "Add",

    // Common
    "common.loading": "Loading...",
    "common.noData": "No data available",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.confirm": "Confirm",
    "common.search": "Search...",
    "common.page": "Page",
    "common.actions": "Actions",
    "common.name": "Name",
    "common.phone": "Phone",
    "common.email": "Email",
    "common.address": "Address",
    "common.createdAt": "Created date",
    "common.group": "Group",
    "common.birthDate": "Birth date",
    "common.notFound": "Not found",
    "common.status": "Status",

    // Teacher page
    "teacher.notFound": "No teachers found.",
    "teacher.deleteTitle": "Delete teacher",
    "teacher.deleteConfirm": "Are you sure you want to delete?",
    "teacher.searchPlaceholder": "Search...",

    // Student page
    "student.notFound": "No students found.",
    "student.searchPlaceholder": "Search student...",
    "student.deleteTitle": "Delete student",
    "student.deleteConfirm": "Are you sure you want to delete?",

    // Groups page
    "group.notFound": "No groups found.",
    "group.searchPlaceholder": "Search group...",
    "group.deleteTitle": "Delete group",
    "group.deleteConfirm": "Are you sure you want to delete?",
    "group.course": "Course",
    "group.teacher": "Teacher",
    "group.studentsCount": "Students count",
    "group.startDate": "Start date",
    "group.endDate": "End date",
    "group.days": "Days",
    "group.time": "Time",
    "group.room": "Room",

    // GroupDetails page
    "groupDetail.info": "Information",
    "groupDetail.syllabus": "Group Textbooks",
    "groupDetail.attendance": "Academic Attendance",
    "groupDetail.mentors": "Group Mentors",
    "groupDetail.params": "Parameters",
    "groupDetail.schedule": "Class Schedule",
    "groupDetail.statistics": "Statistics",
    "groupDetail.active": "Active",
    "groupDetail.inactive": "Inactive",
    "groupDetail.currentMonth": "Current month",
    "groupDetail.showAll": "Show all",
    "groupDetail.showLess": "Show less",
    "groupDetail.noLessons": "No lessons scheduled for this month.",
    "groupDetail.homework": "Homework",
    "groupDetail.videos": "Videos",
    "groupDetail.exams": "Exams",
    "groupDetail.journal": "Journal",
    "groupDetail.newExam": "New Exam",
    "groupDetail.addVideo": "Add",
    "groupDetail.noHomework": "No homework in this group yet.",
    "groupDetail.noVideos": "No videos uploaded in this group yet.",
    "groupDetail.journalEmpty": "Journal section is not available yet",
    "groupDetail.topic": "Topic",
    "groupDetail.givenTime": "Given time",
    "groupDetail.endTime": "End time",
    "groupDetail.lessonDate": "Lesson date",
    "groupDetail.videoName": "Video name",
    "groupDetail.lessonName": "Lesson name",
    "groupDetail.size": "Size",
    "groupDetail.addedTime": "Added time",
    "groupDetail.studentName": "Student name",
    "groupDetail.total": "Total",
    "groupDetail.noStudents": "No students found.",
    "groupDetail.loading": "Loading...",
    "groupDetail.attendanceLoading": "Loading attendance...",
    "groupDetail.uploadVideoTitle": "Click this area or drag a file here to upload a video",
    "groupDetail.uploadVideoFormat": "Video file must be in one of these formats: .mp4, .webm, .mpeg, .avi, .mkv, .m4v, .ogm, .mov",
    "groupDetail.selectLesson": "Select a lesson",
    "groupDetail.uploadFiles": "Upload files",
    "groupDetail.videoLoading": "Video loading...",
    "groupDetail.examName": "Exam name",
    "groupDetail.examStartTime": "Start time",
    "groupDetail.examDuration": "Duration (minutes)",
    "groupDetail.courseLabel": "Course:",
    "groupDetail.avgAge": "Average age:",
    "groupDetail.capacity": "Capacity:",
    "groupDetail.currentStudents": "Current students:",
    "groupDetail.monthlyLessons": "Lessons per month:",
    "groupDetail.courseDuration": "Course duration (months):",
    "groupDetail.totalLessons": "Total lessons:",
    "homeworkDetail.waiting": "Waiting",
    "homeworkDetail.returned": "Returned",
    "homeworkDetail.accepted": "Accepted",
    "homeworkDetail.unsubmitted": "Not submitted",
    "homeworkDetail.gradeHomework": "Grade Homework",
    "homeworkDetail.submittedTime": "Submitted time:",
    "homeworkDetail.notSubmitted": "Not submitted",
    "homeworkDetail.filesCount": "Files / Links count:",
    "homeworkDetail.status": "Current status:",
    "homeworkDetail.studentComment": "Student comment and links:",
    "homeworkDetail.gradingBanner": "Homework graded 60-100 is 'Accepted', 0-59 is 'Returned'.",
    "homeworkDetail.score": "Score",
    "homeworkDetail.passingScore": "Passing score: 60",
    "homeworkDetail.teacherCommentPlaceholder": "Your comment",
    "homeworkDetail.voiceInput": "Voice input",
    "homeworkDetail.studentName": "Student name",
    "homeworkDetail.submittedAt": "Homework submitted time",
    "homeworkDetail.sectionEmpty": "No students in this section",
    "homeworkDetail.successGraded": "Score and comment successfully sent!",
    "examDetail.examTask": "Exam task",
    "examDetail.examComment": "Exam description:",
    "examDetail.studentList": "Student list",
    "examDetail.noStudentsSubmitted": "No students submitted",
    "examDetail.successScore": "Score successfully sent!",
    "lessonAttendance.backToGroup": "Back to group",
    "lessonAttendance.lessonAttendance": "Lesson attendance",
    "lessonAttendance.info": "Information",
    "lessonAttendance.lessonDate": "Lesson date",
    "lessonAttendance.status": "Status",
    "lessonAttendance.lessonCompleted": "Lesson completed",
    "lessonAttendance.lessonNotCompleted": "Lesson not completed",
    "lessonAttendance.attendanceAndTopic": "Attendance and topic entry",
    "lessonAttendance.bySyllabus": "By syllabus",
    "lessonAttendance.other": "Other",
    "lessonAttendance.topic": "Topic",
    "lessonAttendance.descriptionOptional": "Description (optional)",
    "lessonAttendance.descriptionPlaceholder": "Additional lesson info...",
    "lessonAttendance.attended": "Attended",
    "lessonAttendance.lessonAlreadySaved": "Lesson already saved",
    "createHomework.createHomework": "Create new homework",
    "createHomework.createExam": "Create exam",
    "createHomework.selectTopic": "Select a topic",
    "createHomework.loadingTopics": "Loading topics...",
    "createHomework.description": "Description",
    "createHomework.descriptionPlaceholderHW": "Enter detailed homework information...",
    "createHomework.descriptionPlaceholderExam": "Enter detailed exam information...",
    "createHomework.selectFileOrDrag": "Choose file or drag here",
    "createHomework.allowedFormats": "PDF, Word, ZIP and other formats",
    "createHomework.publish": "Publish",
    "createHomework.selectTopicError": "Please select a topic!",
    "createHomework.enterCommentError": "Please enter a description!",
    "createHomework.successPublish": "Homework successfully published!",
    "createHomework.successPublishExam": "Exam successfully created!",
    "createHomework.examWarningBanner": "You can only select topics without homework from the last 7 days!",
    "createHomework.enterEndDateError": "Please enter end date!",
    "createHomework.enterEndTimeError": "Please enter end time!",
    "createHomework.endDate": "End date",
    "createHomework.endTime": "End time",
    "createHomework.enterDatePlaceholder": "Enter date",
    "createHomework.enterTimePlaceholder": "Enter time",
    "createHomework.upload": "Upload",
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return window.localStorage.getItem("app_lang") || "uz";
  });

  useEffect(() => {
    window.localStorage.setItem("app_lang", language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations["uz"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
